version: 2.1
jobs:
    build:    
        docker:
            # specify the version you desire here
            - image: circleci/node:13.5.0
              
        steps:
            - checkout
            - run: npm install
            - run: npm test
