version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
    docker:
        # specify the version you desire here
        - image: circleci/node:13.5.0
              
    steps:
        - checkout
        - run: npm install
        - run: npm test

workflows:
    build-and-test:
      jobs:
        - build-and-test
